### ISSUE TITLE
Unable to create a Element Template for a bpmn:ReceiveTask

### ISSUE THREAD

**Issue by michaelarnauts** [camunda/element-templates-json-schema#127] opened 2024-01-16 10:15 UTC
### Describe the Bug

Looking at the release notes of the Modeller 5.18, and these issues:
* https://github.com/camunda/camunda-modeler/issues/3573
* https://github.com/camunda/element-templates-json-schema/pull/118
* https://github.com/camunda/camunda-modeler/pull/3990

I would assume I can create templates for a `bpmn:ReceiveTask`.

### Steps to Reproduce

Try to validate the following Element Template:
```
{
  "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
  "name": "Example Receive Task",
  "id": "com.camunda.example.ReceiveTask",
  "appliesTo": [
    "bpmn:ReceiveTask"
  ],
  "elementType": {
    "value": "bpmn:ReceiveTask",
    "eventDefinition": "bpmn:MessageEventDefinition"
  },
  "properties": []
}
```
I get the error that "Value "bpmn:ReceiveTask" is not defined in enum."

![image](https://github.com/camunda/element-templates-json-schema/assets/1193779/51c6e9c7-a3f3-4e53-979e-15a745ab4f2c)

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 0.3.0]

**Comment by barmac** [comment] 2024-01-23 11:13
Hi,

In BPMN 2.0, Receive Task doesn't have event definition. This is allowed only in events. So to make your template valid, you need to remove the `eventDefinition` property.

I am closing this issue as it's not a bug.

**Closed by barmac** 2024-01-23 11:13 UTC
Labels: bug

**Comment by barmac** [comment] 2024-01-23 11:15
If you want to template `bpmn:Message#property` in Receive Task, you need to only specify the `elementType#value` or set `allowedIn` to `[ "bpmn:ReceiveTask" ]`. Let me know if there are any problems after adjustment.
